Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
