Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 423, in train
    self.flatten_data(self.unseen_data),
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 484, in flatten_data
    gs, ys = data
ValueError: not enough values to unpack (expected 2, got 0)
Using backend: pytorch
Traceback (most recent call last):
  File "scripts/active/belief_active_plot.py", line 640, in <module>
    best_df, pro_ts_df, retro_ts_df = plot.generate()
  File "scripts/active/belief_active_plot.py", line 257, in generate
    final_results, prospective_beliefs, retrospective_beliefs = self.run_trials(ds)
  File "scripts/active/belief_active_plot.py", line 327, in run_trials
    acquisitions = self.bo.run(num_rounds=self.num_rounds)
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 388, in run
    self.train()
  File "/home/nguyenm5/coding/pinot/pinot/active/experiment.py", line 464, in train
    self.net = pinot.app.experiment.Train(
  File "/home/nguyenm5/coding/pinot/pinot/app/experiment.py", line 117, in train
    epoch_loss = self.train_once()
  File "/home/nguyenm5/coding/pinot/pinot/app/experiment.py", line 92, in train_once
    loss = torch.sum(self.net.loss(*x))
  File "/home/nguyenm5/coding/pinot/pinot/generative/semi_supervised_net.py", line 155, in loss
    total_loss = self.loss_unsupervised(g, h) * self.unsup_scale
  File "/home/nguyenm5/coding/pinot/pinot/generative/semi_supervised_net.py", line 267, in loss_unsupervised
    recon_loss = self.decoder.decode_and_compute_recon_error(g, z_sample)
  File "/home/nguyenm5/coding/pinot/pinot/generative/decoder.py", line 311, in decode_and_compute_recon_error
    E_true = self.edge_tensor_from_g(subgraph)
  File "/home/nguyenm5/coding/pinot/pinot/generative/decoder.py", line 259, in edge_tensor_from_g
    E = one_hot_no_bond.repeat(n, n, 1)
KeyboardInterrupt
